# Columns to keep in the dataset
columns_to_keep:
  - RUN_DATETIME
  - INTERVAL_DATETIME
  - REGIONID
  - RRP
  - ROP
  - RAISE6SECRRP
  - RAISE6SECROP
  - RAISE60SECRRP
  - RAISE60SECROP
  - RAISE5MINRRP
  - RAISE5MINROP
  - RAISEREGRRP
  - RAISEREGROP
  - LOWER6SECRRP
  - LOWER6SECROP
  - LOWER60SECRRP
  - LOWER60SECROP
  - LOWER5MINRRP
  - LOWER5MINROP
  - LOWERREGRRP
  - LOWERREGROP
  - TOTALDEMAND
  - AVAILABLEGENERATION
  - AVAILABLELOAD
  - DEMANDFORECAST
  - DISPATCHABLEGENERATION
  - LOWER5MINLOCALDISPATCH
  - LOWER60SECLOCALDISPATCH
  - LOWER6SECLOCALDISPATCH
  - RAISE5MINLOCALDISPATCH
  - RAISE60SECLOCALDISPATCH
  - RAISE6SECLOCALDISPATCH
  - AGGREGATEDISPATCHERROR
  - INITIALSUPPLY
  - CLEAREDSUPPLY
  - LOWERREGLOCALDISPATCH
  - RAISEREGLOCALDISPATCH
  - TOTALINTERMITTENTGENERATION
  - DEMAND_AND_NONSCHEDGEN
  - UIGF
  - SEMISCHEDULE_CLEAREDMW
  - SEMISCHEDULE_COMPLIANCEMW
  - SS_SOLAR_UIGF
  - SS_WIND_UIGF
  - SS_SOLAR_CLEAREDMW
  - SS_WIND_CLEAREDMW
  - SS_SOLAR_COMPLIANCEMW
  - SS_WIND_COMPLIANCEMW